Cyprian my branch
NethermindEth/latticefold pull request #169
Opened 2024-12-28 11:24 UTC by cypriansakwa

1. Added detailed project overview, applications and features of LatticeFold.
2. Included build troubleshooting tips.
3. Enhanced Prerequisites and Instructions
4. Under Frontends, showed the essence of R1CS and CCS, highlighting their roles in representing arithmetic circuits and providing flexible circuit definitions, respectively.
5. Highlighted how to Run an example using Cargo.
6. Improved formatting and added a Table of Contents.

2024-12-28 11:45 UTC, cypriansakwa commented
I am Cyprian Sakwa a PhD intern at Nethermind currently working on cryptography research. @NethermindEth, please review this pull request.

2025-01-15 11:28 UTC, cypriansakwa commented
Hi. How are you today? I request for your review here.  @ElijahVlasov , @cypriansakwa , @matthew-a-klein , @ivolkg , @v0-e , @tkstanczak , @tkstanczak , @frozenspider . Thanks.

2025-01-17 06:34 UTC, cypriansakwa commented
Hi @ivolkg , @matthew-a-klein , @ElijahVlasov , @v0-e , @cupicmarko , @Fantoni0 , @miha-stopar , @maksimryndin , @tkstanczak . I hope this message finds you well. This is a gentle reminder regarding a pull request I submitted, which is currently awaiting review: https://github.com/NethermindEth/latticefold/pulls . I would greatly appreciate your feedback or any comments you may have. If there are any issues or concerns with the pull request, please feel free to let me know here, and I will be happy to address them promptly.
Thank you for your time and consideration.
Best regards,  
Cyprian Sakwa

2025-01-17 12:37 UTC, ElijahVlasov commented on README.md
> +---
Is it common for repos to have a table of content?

2025-01-17 12:39 UTC, ElijahVlasov commented on README.md
> +- **Zero-Knowledge Proofs**: Prove knowledge of a statement without revealing the statement itself.
What's the difference between privacy-preserving and zero knowledge?

2025-01-17 12:42 UTC, ElijahVlasov commented on README.md
> +- One can install the `nightly-2024-11-05` toolchain by invoking:
Why mention it twice?

2025-01-17 12:43 UTC, ElijahVlasov commented on README.md
> +Currently, the only way to define a circuit to be folded is by specifying it as a [rank-1 constraint system (R1CS)](https://github.com/NethermindEth/latticefold/blob/main/latticefold/src/arith/r1cs.r
R1CS's are special case of degree-2 constraints, CCS's are arbitrary constraints of any degree

2025-01-17 12:44 UTC, ElijahVlasov requested changes
Left a few comments.

2025-01-17 15:13 UTC, cypriansakwa commented on README.md
> +---
Hi @ElijahVlasov . Thank you for your feedback! Including a table of contents can be helpful, especially for repositories with lengthy or detailed README files. It improves navigation by allowing users to quickly jump to the sections they’re most interested in, enhancing the overall user experience.

That said, I understand it might not be common in all repositories. If it’s unnecessary or inconsistent with the repository's style, I’d be happy to adjust or remove it as needed. Please let me know your thoughts!

Best regards,

2025-01-17 15:26 UTC, cypriansakwa commented on README.md
> +- **Zero-Knowledge Proofs**: Prove knowledge of a statement without revealing the statement itself.
Thank you for your feedback! I appreciate you pointing out that the mentioned applications might not be directly applicable to Latticefold. To maintain accuracy and clarity, I’ll go ahead and remove that section from the pull request.

2025-01-17 15:30 UTC, cypriansakwa commented on README.md
> +- Ensure `rustup` is installed to manage toolchains.
Thanks for pointing out. I have removed one to avoid repetition.

2025-01-17 15:41 UTC, cypriansakwa commented on README.md
> +- One can install the `nightly-2024-11-05` toolchain by invoking:
Thank you for catching that repetition! I’ll remove the redundant mention of installing the nightly-2024-11-05 toolchain to make the documentation more concise.

2025-01-17 15:54 UTC, cypriansakwa commented on README.md
> +Currently, the only way to define a circuit to be folded is by specifying it as a [rank-1 constraint system (R1CS)](https://github.com/NethermindEth/latticefold/blob/main/latticefold/src/arith/r1cs.r
Thank you for your valuable feedback. You are correct that R1CS is a special case of degree-2 constraints, while CCS can handle constraints of any degree. I have revised the statement accordingly to reflect this distinction more accurately

2025-01-17 16:11 UTC, cypriansakwa commented on README.md
> +LatticeFold is a proof-of-concept implementation of the LatticeFold folding scheme engineered by [Nethermind](https://nethermind.io) based on the work
Thank you for your feedback. Based on your suggestion, we have revised the statement for clarity and readability.

2025-01-21 05:11 UTC, cypriansakwa commented
Dear @ElijahVlasov ,

I hope this message finds you well. I am writing to inform you that I have implemented the changes you requested during your review. The modifications have been incorporated in line with your feedback, and I believe they address the concerns raised.

I kindly ask you to review the updated work at your earliest convenience and provide any additional advice or suggestions. Your guidance is invaluable, and I look forward to your insights.

Thank you for your time and support.

Best regards Cyprian Sakwa, Nethermind's intern

2025-02-03 05:17 UTC, cypriansakwa reviewed
Subject: Follow-Up on Pull Request Review
Hi @ElijahVlasov 
I hope you're doing well.
I made the requested changes to my pull request based on your feedback. When you have a moment, could you please take another look and let me know if anything else needs adjustment?
I appreciate your time and guidance. Looking forward to your thoughts!
Best,
Cyprian Sakwa

2025-02-08 04:40 UTC, cypriansakwa commented
Subject: Follow-Up on Pull Request ReviewHi @ivolkg , @matthew-a-klein , @ElijahVlasov , @v0-e , @cupicmarko , @Fantoni0 , @miha-stopar , @maksimryndin , @tkstanczak . I hope you're doing well.
I made the requested changes to my pull request based on your feedback. When you have a moment, could you please take another look and let me know if anything else needs adjustment?
I appreciate your time and guidance. Looking forward to your thoughts!
Best,
Cyprian Sakwa

2025-04-30 08:38 UTC, closed without merging